### ISSUE TITLE
Value error due to unequal label sequence lengths

### ISSUE THREAD

**Issue by yanyu9385** [coastalcph/fairlex#2]
For the ECtHR dataset, the label sequence lengths are unequal. Could you advise how you handled the value error in “ecthr_dataset.py”?
 
![Value error due to unequal label sequence lengths](https://github.com/coastalcph/fairlex/assets/109617122/36e6a29f-5eb6-44f6-b458-f1d13a54ea4d)

**Comment by iliaschalkidis** [comment]
Hi @yanyu9385,

I made some changes to fix this bug. Can you update and let me know, if everything is working fine?

**Comment by yanyu9385** [comment]
I am happy to report that after applying the code update you provided, the program is now functioning smoothly. Thank you again for all of your help.

**Comment by iliaschalkidis** [comment]
I'm glad it's working, and thanks for reporting this bug. Let me know, if you have any other issues in the near future.
